import PDFDocument from "pdfkit";

export type BookingPdfInput = {
  orgName: string;
  bookingRef: string;
  generatedAt: Date;
  projectName: string;
  unitNumber: string;
  floor: number;
  bedrooms: number;
  areaSqFt: string;
  priceListedRs: number;
  priceFinalRs: number | null;
  leadName: string;
  leadPhone: string | null;
  agentName: string;
};

function formatInr(value: number): string {
  return value.toLocaleString("en-IN");
}

function formatDate(date: Date): string {
  return date.toLocaleDateString("en-IN", { dateStyle: "long" });
}

function formatDateTime(date: Date): string {
  return date.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });
}

export function buildBookingPdfBuffer(input: BookingPdfInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).font("Helvetica-Bold").text("PropNinja CRM", { align: "center" });
    doc.moveDown(0.25);
    doc.fontSize(12).font("Helvetica").text(input.orgName, { align: "center" });
    doc.moveDown(1.5);

    doc.fontSize(18).font("Helvetica-Bold").text("Booking Summary", { align: "center" });
    doc.moveDown(1.25);

    const lineGap = 8;
    doc.fontSize(11).font("Helvetica");

    const rows: Array<[string, string]> = [
      ["Date", formatDate(input.generatedAt)],
      ["Booking Reference", input.bookingRef],
      ["Property", input.projectName],
      ["Unit", `${input.unitNumber} | Floor: ${input.floor} | ${input.bedrooms}BHK`],
      ["Area", `${input.areaSqFt} sq ft`],
      ["Listed Price", `₹${formatInr(input.priceListedRs)}`],
      ["Final Price", input.priceFinalRs != null ? `₹${formatInr(input.priceFinalRs)}` : "TBD"],
      ["Lead Name", input.leadName],
      ["Lead Phone", input.leadPhone ?? "—"],
      ["Assigned Agent", input.agentName],
    ];

    for (const [label, value] of rows) {
      doc.font("Helvetica-Bold").text(`${label}:`, { continued: true, lineGap });
      doc.font("Helvetica").text(` ${value}`, { lineGap });
    }

    doc.moveDown(2);
    doc
      .fontSize(9)
      .fillColor("#666666")
      .text(`Generated by PropNinja CRM on ${formatDateTime(input.generatedAt)}`, {
        align: "center",
      });

    doc.end();
  });
}

export function buildBookingRef(unitId: string, date = new Date()): string {
  const year = date.getFullYear();
  const suffix = unitId.replace(/-/g, "").slice(-6).toUpperCase();
  return `BOOK-${year}-${suffix}`;
}

export function buildBookingFileKey(projectId: string, unitId: string, date = new Date()): string {
  const datePart = date.toISOString().slice(0, 10);
  return `bookings/${projectId}/${unitId}-booking-${datePart}.pdf`;
}
