/** Module-level permissions. Admin role bypasses all checks in hasPermission(). */
export const PERMISSIONS = {
  masterData: {
    search: "master_data:search",
  },
  dashboard: {
    view: "dashboard:view",
    viewTeam: "dashboard:view_team",
    viewOrg: "dashboard:view_org",
  },
  users: {
    view: "users:view",
    search: "users:search",
    viewForFilter: "users:view_for_filter",
    create: "users:create",
    update: "users:update",
    delete: "users:delete",
    export: "users:export",
  },
  userProfile: {
    view: "user_profile:view",
    update: "user_profile:update",
  },
  userRoles: {
    view: "user_roles:view",
    update: "user_roles:update",
  },
  leads: {
    view: "leads:view",
    search: "leads:search",
    create: "leads:create",
    update: "leads:update",
    delete: "leads:delete",
    assign: "leads:assign",
    viewAll: "leads:view_all",
    viewLeadSource: "leads:view_lead_source",
    bulkUpload: "leads:bulk_upload",
    updateBasicInfo: "leads:update_basic_info",
    updateLeadStatus: "leads:update_lead_status",
    updateNotes: "leads:update_notes",
    updateDocuments: "leads:update_documents",
    updateTags: "leads:update_tags",
    communications: "leads:communications",
    export: "leads:export",
  },
  properties: {
    view: "properties:view",
    search: "properties:search",
    create: "properties:create",
    update: "properties:update",
    delete: "properties:delete",
    bulkUpload: "properties:bulk_upload",
    viewAssigned: "properties:view_assigned",
    assign: "properties:assign",
    updateDocuments: "properties:update_documents",
    bulkReassign: "properties:bulk_reassign",
  },
  tasks: {
    view: "tasks:view",
    search: "tasks:search",
    create: "tasks:create",
    update: "tasks:update",
    delete: "tasks:delete",
  },
  integration: {
    view: "integration:view",
    delete: "integration:delete",
    assign: "integration:assign",
    search: "integration:search",
    create: "integration:create",
    update: "integration:update",
    cloneProperty: "integration:clone_property",
  },
  teams: {
    view: "teams:view",
  },
  orgProfile: {
    view: "org_profile:view",
    search: "org_profile:search",
    create: "org_profile:create",
    update: "org_profile:update",
    delete: "org_profile:delete",
  },
  projects: {
    view: "projects:view",
    search: "projects:search",
    create: "projects:create",
    update: "projects:update",
    delete: "projects:delete",
    assign: "projects:assign",
    bulkUpload: "projects:bulk_upload",
    viewAssigned: "projects:view_assigned",
    updateDocuments: "projects:update_documents",
    export: "projects:export",
  },
  data: {
    view: "data:view",
    search: "data:search",
    create: "data:create",
    update: "data:update",
    assign: "data:assign",
    bulkUpload: "data:bulk_upload",
  },
  media: {
    view: "media:view",
    search: "media:search",
    create: "media:create",
    update: "media:update",
    delete: "media:delete",
  },
  invoice: {
    view: "invoice:view",
    search: "invoice:search",
    delete: "invoice:delete",
    viewBrokerageInfo: "invoice:view_brokerage_info",
    update: "invoice:update",
    assign: "invoice:assign",
  },
  listingIntegration: {
    view: "listing_integration:view",
    search: "listing_integration:search",
    create: "listing_integration:create",
    update: "listing_integration:update",
    cloneProperty: "listing_integration:clone_property",
  },
  listing: {
    view: "listing:view",
    search: "listing:search",
    create: "listing:create",
    update: "listing:update",
    cloneProperty: "listing:clone_property",
    bulkUpload: "listing:bulk_upload",
    viewAssigned: "listing:view_assigned",
    assign: "listing:assign",
  },
  reports: {
    view: "reports:view",
    viewAll: "reports:view_all",
    viewReportees: "reports:view_reportees",
    export: "reports:export",
    exportReportees: "reports:export_reportees",
  },
  roles: {
    view: "roles:view",
    create: "roles:create",
    update: "roles:update",
    delete: "roles:delete",
  },
  acl: {
    view: "permissions:view",
    update: "permissions:update",
  },
  settings: {
    view: "settings:view",
    update: "settings:update",
  },
} as const;

type FlattenPermissions<T> = T extends Record<string, string> ? T[keyof T] : never;
export type Permission = FlattenPermissions<(typeof PERMISSIONS)[keyof typeof PERMISSIONS]>;

export type UserRole = "admin" | "manager" | "agent";

export function roleHasPermission(role: UserRole | string, permission: Permission): boolean {
  if (role === "admin") return true;
  if (role === "manager") return MANAGER_PERMISSIONS.includes(permission);
  if (role === "agent") return AGENT_PERMISSIONS.includes(permission);
  return false;
}

/** Permissions granted to manager role (from product access matrix). */
export const MANAGER_PERMISSIONS: Permission[] = [
  PERMISSIONS.masterData.search,
  PERMISSIONS.dashboard.view,
  PERMISSIONS.dashboard.viewTeam,
  PERMISSIONS.users.view,
  PERMISSIONS.users.search,
  PERMISSIONS.users.create,
  PERMISSIONS.users.update,
  PERMISSIONS.users.delete,
  PERMISSIONS.users.viewForFilter,
  PERMISSIONS.userProfile.view,
  PERMISSIONS.userProfile.update,
  PERMISSIONS.userRoles.view,
  PERMISSIONS.userRoles.update,
  PERMISSIONS.roles.view,
  PERMISSIONS.roles.update,
  PERMISSIONS.roles.create,
  PERMISSIONS.roles.delete,
  PERMISSIONS.acl.view,
  PERMISSIONS.acl.update,
  PERMISSIONS.leads.view,
  PERMISSIONS.leads.search,
  PERMISSIONS.leads.create,
  PERMISSIONS.leads.update,
  PERMISSIONS.leads.assign,
  PERMISSIONS.leads.viewLeadSource,
  PERMISSIONS.leads.bulkUpload,
  PERMISSIONS.leads.updateBasicInfo,
  PERMISSIONS.leads.updateLeadStatus,
  PERMISSIONS.leads.updateNotes,
  PERMISSIONS.leads.updateDocuments,
  PERMISSIONS.leads.updateTags,
  PERMISSIONS.leads.communications,
  PERMISSIONS.properties.view,
  PERMISSIONS.properties.search,
  PERMISSIONS.properties.create,
  PERMISSIONS.properties.update,
  PERMISSIONS.properties.delete,
  PERMISSIONS.properties.bulkUpload,
  PERMISSIONS.properties.viewAssigned,
  PERMISSIONS.properties.assign,
  PERMISSIONS.properties.updateDocuments,
  PERMISSIONS.properties.bulkReassign,
  PERMISSIONS.tasks.view,
  PERMISSIONS.tasks.search,
  PERMISSIONS.tasks.create,
  PERMISSIONS.tasks.update,
  PERMISSIONS.tasks.delete,
  PERMISSIONS.integration.assign,
  PERMISSIONS.integration.view,
  PERMISSIONS.integration.search,
  PERMISSIONS.integration.create,
  PERMISSIONS.integration.update,
  PERMISSIONS.integration.cloneProperty,
  PERMISSIONS.orgProfile.view,
  PERMISSIONS.orgProfile.search,
  PERMISSIONS.orgProfile.create,
  PERMISSIONS.orgProfile.update,
  PERMISSIONS.orgProfile.delete,
  PERMISSIONS.projects.view,
  PERMISSIONS.projects.search,
  PERMISSIONS.projects.create,
  PERMISSIONS.projects.update,
  PERMISSIONS.projects.assign,
  PERMISSIONS.projects.delete,
  PERMISSIONS.projects.bulkUpload,
  PERMISSIONS.projects.viewAssigned,
  PERMISSIONS.projects.updateDocuments,
  PERMISSIONS.data.view,
  PERMISSIONS.data.search,
  PERMISSIONS.data.create,
  PERMISSIONS.data.update,
  PERMISSIONS.data.assign,
  PERMISSIONS.data.bulkUpload,
  PERMISSIONS.media.view,
  PERMISSIONS.media.search,
  PERMISSIONS.media.create,
  PERMISSIONS.media.update,
  PERMISSIONS.media.delete,
  PERMISSIONS.invoice.view,
  PERMISSIONS.invoice.search,
  PERMISSIONS.invoice.delete,
  PERMISSIONS.invoice.viewBrokerageInfo,
  PERMISSIONS.invoice.update,
  PERMISSIONS.invoice.assign,
  PERMISSIONS.listingIntegration.view,
  PERMISSIONS.listingIntegration.search,
  PERMISSIONS.listingIntegration.create,
  PERMISSIONS.listingIntegration.update,
  PERMISSIONS.listingIntegration.cloneProperty,
  PERMISSIONS.listing.view,
  PERMISSIONS.listing.search,
  PERMISSIONS.listing.create,
  PERMISSIONS.listing.update,
  PERMISSIONS.listing.cloneProperty,
  PERMISSIONS.listing.bulkUpload,
  PERMISSIONS.listing.viewAssigned,
  PERMISSIONS.listing.assign,
  PERMISSIONS.reports.view,
  PERMISSIONS.reports.viewReportees,
  PERMISSIONS.reports.exportReportees,
];

/** Agent role permissions (from product access matrix). */
export const AGENT_PERMISSIONS: Permission[] = [
  PERMISSIONS.masterData.search,
  PERMISSIONS.dashboard.view,
  PERMISSIONS.dashboard.viewTeam,
  PERMISSIONS.users.viewForFilter,
  PERMISSIONS.userProfile.view,
  PERMISSIONS.userProfile.update,
  PERMISSIONS.leads.view,
  PERMISSIONS.leads.search,
  PERMISSIONS.leads.create,
  PERMISSIONS.leads.update,
  PERMISSIONS.leads.assign,
  PERMISSIONS.leads.viewLeadSource,
  PERMISSIONS.leads.bulkUpload,
  PERMISSIONS.leads.updateBasicInfo,
  PERMISSIONS.leads.updateLeadStatus,
  PERMISSIONS.leads.updateNotes,
  PERMISSIONS.leads.updateDocuments,
  PERMISSIONS.leads.updateTags,
  PERMISSIONS.leads.communications,
  PERMISSIONS.properties.view,
  PERMISSIONS.properties.search,
  PERMISSIONS.properties.create,
  PERMISSIONS.properties.update,
  PERMISSIONS.properties.bulkUpload,
  PERMISSIONS.properties.viewAssigned,
  PERMISSIONS.properties.assign,
  PERMISSIONS.properties.updateDocuments,
  PERMISSIONS.tasks.view,
  PERMISSIONS.integration.view,
  PERMISSIONS.integration.delete,
  PERMISSIONS.integration.assign,
  PERMISSIONS.integration.search,
  PERMISSIONS.integration.create,
  PERMISSIONS.integration.update,
  PERMISSIONS.integration.cloneProperty,
  PERMISSIONS.teams.view,
  PERMISSIONS.orgProfile.view,
  PERMISSIONS.orgProfile.search,
  PERMISSIONS.projects.view,
  PERMISSIONS.projects.search,
  PERMISSIONS.projects.create,
  PERMISSIONS.projects.update,
  PERMISSIONS.projects.assign,
  PERMISSIONS.projects.bulkUpload,
  PERMISSIONS.projects.viewAssigned,
  PERMISSIONS.projects.updateDocuments,
  PERMISSIONS.data.view,
  PERMISSIONS.data.search,
  PERMISSIONS.data.create,
  PERMISSIONS.data.update,
  PERMISSIONS.data.assign,
  PERMISSIONS.data.bulkUpload,
  PERMISSIONS.media.view,
  PERMISSIONS.media.search,
  PERMISSIONS.media.create,
  PERMISSIONS.media.update,
  PERMISSIONS.invoice.view,
  PERMISSIONS.invoice.search,
  PERMISSIONS.invoice.delete,
  PERMISSIONS.invoice.viewBrokerageInfo,
  PERMISSIONS.invoice.update,
  PERMISSIONS.invoice.assign,
  PERMISSIONS.listingIntegration.view,
  PERMISSIONS.listingIntegration.search,
  PERMISSIONS.listingIntegration.create,
  PERMISSIONS.listingIntegration.update,
  PERMISSIONS.listingIntegration.cloneProperty,
  PERMISSIONS.listing.view,
  PERMISSIONS.listing.search,
  PERMISSIONS.listing.create,
  PERMISSIONS.listing.update,
  PERMISSIONS.listing.cloneProperty,
  PERMISSIONS.listing.bulkUpload,
  PERMISSIONS.listing.viewAssigned,
  PERMISSIONS.listing.assign,
];
